"""Initial migration.

Revision ID: acfbc821d047
Revises: 
Create Date: 2021-05-30 20:55:45.143292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfbc821d047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA app")
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('reciever', sa.Integer(), nullable=False),
    sa.Column('datecreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body'),
    sa.UniqueConstraint('reciever'),
    sa.UniqueConstraint('sender'),
    schema='app'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=50), nullable=False),
    sa.Column('last', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first'),
    sa.UniqueConstraint('last'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='app')
    op.drop_table('chat', schema='app')
    op.execute("DROP SCHEMA app")
    # ### end Alembic commands ###
